### ISSUE TITLE
作者がホモ

### ISSUE THREAD

**Issue by sudosanet** [tumugin/NowplayingTunes#7]
バグですか？

**Comment by tumugin** [comment]
![aaaacojtuj36w snapshot](https://cloud.githubusercontent.com/assets/1785179/6597156/e58c6fa0-c83d-11e4-8ed7-b8f90a2f774c.jpg)
作者はノンケだってはっきりわかんだね

**Comment by sudosanet** [comment]
やっぱりホモじゃないか！（歓喜）
